javascript:
  dest:
    root: "."
    buildDir: "_site/assets/js/"
  # filename to output
  filename: "script.js"
  notification: "Running JavaScript"
  # Paths to JavaScript libraries, which are combined into one file
  src:
    # Paths to your own project code are here
    # All the files in this list and in the js dir are concatenated into script.js
    - "build/js/*.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    root: "."
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "build/sass/main.scss"

watch:
  javascript: "build/js/**/*.js"
  sass: "build/sass/**/*.scss"