javascript:
  dest:
    root: "."
    buildDir: "_site/assets/js/"
  front:
    # filename to output
    filename: "script.js"
    notification: "Running JavaScript"
    # Paths to JavaScript libraries, which are combined into one file
    src:
      # Paths to your own project code are here
      # All the files in this list and in the js dir are concatenated into script.js
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
  admin:
    filename: "admin.js"
    notification: "Running Admin JavaScript"
    src:
      - "build/js/admin/**/*.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    root: "."
    buildDir: "_site/assets/css/"
  front:
    notification: "Running Sass"
    src: "build/sass/main.scss"
  admin:
    notification: "Running Admin Sass"
    src: "build/sass/admin/main.scss"

watch:
  javascript:
    front:
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
    admin: "build/js/admin/**/*.js"
  sass: 
    front: 
      - "build/sass/**/*.scss"
      - "!build/sass/admin/**/*.scss"
    admin: "build/sass/admin/**/*.scss"
