javascript:
  front:
    root: "./assets/js"
    filename: "front.js"
    notification: "Running Front Javascript"
    src:
      - "build/js/front/**/*.js"
  admin:
    root: "./assets/js"
    filename: "admin.js"
    vendor:
      - "bower_components/jquery.repeater/jquery.repeater.min.js"
      - "bower_components/foundation-sites/js/foundation.core.js"
      - "bower_components/foundation-sites/js/foundation.util.keyboard.js"
      - "bower_components/foundation-sites/js/foundation.util.box.js"
      - "bower_components/foundation-sites/js/foundation.util.mediaQuery.js"
      - "bower_components/foundation-sites/js/foundation.util.triggers.js"
      - "bower_components/foundation-sites/js/foundation.util.motion.js"
      - "bower_components/foundation-sites/js/foundation.reveal.js"
    notification: "Running Admin JavaScript"
    src:
      - "build/js/admin/**/*.js"
  fes:
    root: "./assets/js/"
    filename: "edd-fields-fes.js"
    notification: "Running FES JavaScript"
    src:
      - "build/js/fes/**/*.js"
  tinymce:
    root: "./assets/js/tinymce/"
    notification: "Running TinyMCE JavaScript"
    src:
      - "build/js/tinymce/**/*.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  front:
    root: "./assets/css"
    filename: "front.css"
    vendor: 
      - ""
    notification: "Running Sass"
    src: "build/sass/front/front.scss"
  admin:
    root: "./assets/css"
    filename: "admin.css"
    vendor:
      - "bower_components/foundation-sites/scss"
    notification: "Running Admin Sass"
    src: "build/sass/admin/main.scss"

watch:
  javascript:
    front: "build/js/front/**/*.js"
    admin: "build/js/admin/**/*.js"
    fes: "build/js/fes/**/*.js"
    tinymce: "build/js/tinymce/**/*.js"
  sass: 
    front: "build/sass/front/**/*.scss"
    admin: "build/sass/admin/**/*.scss"

release:
  type: 'plugin'
  languagesDir: './languages/'
  files:
    - "./**/*.*"
    - "!./**/*.map"
    - "!./**/build/**/*.*"
    - "!./**/.git/**"
    - "!./**/.gitignore"
    - "!./**/.gitmodules"
    - "!./**/gulpfile.js"
    - "!./**/gruntfile.js"
    - "!./**/gulp/**/*.*"
    - "!./**/package.json"
    - "!./**/bower.json"
    - "!./**/composer.json"
    - "!./**/node_modules/**/*.*"
    - "!./**/bower_components/**/*.*"
    - "!./**/README.md"
    - "!./**/*.zip"